//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakePdf.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MakePdf.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Home.
        /// </summary>
        public static string Common_BackHome {
            get {
                return ResourceManager.GetString("Common_BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Common_Down {
            get {
                return ResourceManager.GetString("Common_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion pattern.
        /// </summary>
        public static string Common_ExclusionPattern {
            get {
                return ResourceManager.GetString("Common_ExclusionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Common_Load {
            get {
                return ResourceManager.GetString("Common_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings.
        /// </summary>
        public static string Common_LoadSetting {
            get {
                return ResourceManager.GetString("Common_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Dialog.
        /// </summary>
        public static string Common_OpenFileDialog {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All File.
        /// </summary>
        public static string Common_OpenFileDialog_FileType_All {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_FileType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File.
        /// </summary>
        public static string Common_OpenFileDialog_FileType_Json {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_FileType_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF File.
        /// </summary>
        public static string Common_OpenFileDialog_FileType_Pdf {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_FileType_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings.
        /// </summary>
        public static string Common_OpenFileDialog_Title_LoadSetting {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_Title_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output file.
        /// </summary>
        public static string Common_OpenFileDialog_Title_OutputFile {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_Title_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save setting.
        /// </summary>
        public static string Common_OpenFileDialog_Title_SaveSetting {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_Title_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder dialog.
        /// </summary>
        public static string Common_OpenFolderDialog {
            get {
                return ResourceManager.GetString("Common_OpenFolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select working directory.
        /// </summary>
        public static string Common_OpenFolderDialog_Title_WorkingDirectory {
            get {
                return ResourceManager.GetString("Common_OpenFolderDialog_Title_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string Common_SaveSetting {
            get {
                return ResourceManager.GetString("Common_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Common_Start {
            get {
                return ResourceManager.GetString("Common_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start process.
        /// </summary>
        public static string Common_StartProcess {
            get {
                return ResourceManager.GetString("Common_StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Common_Up {
            get {
                return ResourceManager.GetString("Common_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the working directory..
        /// </summary>
        public static string Dialog_DirectoryEmpty_Message_WorkingDirectory {
            get {
                return ResourceManager.GetString("Dialog_DirectoryEmpty_Message_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory is empty.
        /// </summary>
        public static string Dialog_DirectoryEmpty_Title {
            get {
                return ResourceManager.GetString("Dialog_DirectoryEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to load the new setting file?.
        /// </summary>
        public static string Dialog_DropSettingFile_Message {
            get {
                return ResourceManager.GetString("Dialog_DropSettingFile_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Dialog_DropSettingFile_Title {
            get {
                return ResourceManager.GetString("Dialog_DropSettingFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.
        /// </summary>
        public static string Dialog_FileExists_Message {
            get {
                return ResourceManager.GetString("Dialog_FileExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to overwrite it?.
        /// </summary>
        public static string Dialog_FileExists_Message_Overwrite {
            get {
                return ResourceManager.GetString("Dialog_FileExists_Message_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file exists.
        /// </summary>
        public static string Dialog_FileExists_Title {
            get {
                return ResourceManager.GetString("Dialog_FileExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the output file..
        /// </summary>
        public static string Dialog_FileNameEmpty_Message_OutputFile {
            get {
                return ResourceManager.GetString("Dialog_FileNameEmpty_Message_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is empty.
        /// </summary>
        public static string Dialog_FileNameEmpty_Title {
            get {
                return ResourceManager.GetString("Dialog_FileNameEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting file does not exists..
        /// </summary>
        public static string Dialog_FileNotExists_Message_SettingFile {
            get {
                return ResourceManager.GetString("Dialog_FileNotExists_Message_SettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exists.
        /// </summary>
        public static string Dialog_FileNotExists_Title {
            get {
                return ResourceManager.GetString("Dialog_FileNotExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        public static string Dialog_NewVersionFound_CurrentVersion {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Dialog_NewVersionFound_Later {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version is available..
        /// </summary>
        public static string Dialog_NewVersionFound_Message1 {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update now ?.
        /// </summary>
        public static string Dialog_NewVersionFound_Message2 {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        public static string Dialog_NewVersionFound_NewVersion {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version found.
        /// </summary>
        public static string Dialog_NewVersionFound_Title {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Dialog_NewVersionFound_Update {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        public static string Dialog_Processing_Completed {
            get {
                return ResourceManager.GetString("Dialog_Processing_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for a while..
        /// </summary>
        public static string Dialog_Processing_Started {
            get {
                return ResourceManager.GetString("Dialog_Processing_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Dialog_Processing_Title {
            get {
                return ResourceManager.GetString("Dialog_Processing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It also supports CUI. Please see the help for details..
        /// </summary>
        public static string Home_Cui_Detail1 {
            get {
                return ResourceManager.GetString("Home_Cui_Detail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop files and easily convert to PDF..
        /// </summary>
        public static string Home_Easy_Detail1 {
            get {
                return ResourceManager.GetString("Home_Easy_Detail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to make detailed settings..
        /// </summary>
        public static string Home_Easy_Detail2 {
            get {
                return ResourceManager.GetString("Home_Easy_Detail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set input and output patterns, convert and combine to PDF..
        /// </summary>
        public static string Home_Standard_Detail1 {
            get {
                return ResourceManager.GetString("Home_Standard_Detail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings use regular expressions..
        /// </summary>
        public static string Home_Standard_Detail2 {
            get {
                return ResourceManager.GetString("Home_Standard_Detail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings can be saved in a file..
        /// </summary>
        public static string Home_Standard_Detail3 {
            get {
                return ResourceManager.GetString("Home_Standard_Detail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string Item_After {
            get {
                return ResourceManager.GetString("Item_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All directories.
        /// </summary>
        public static string Item_AllDirectories {
            get {
                return ResourceManager.GetString("Item_AllDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files.
        /// </summary>
        public static string Item_AllSupportedFiles {
            get {
                return ResourceManager.GetString("Item_AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Item_Before {
            get {
                return ResourceManager.GetString("Item_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        public static string Item_Bookmark {
            get {
                return ResourceManager.GetString("Item_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory name to bookmark.
        /// </summary>
        public static string Item_Bookmark_AddDirectoryName {
            get {
                return ResourceManager.GetString("Item_Bookmark_AddDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file name to bookmark.
        /// </summary>
        public static string Item_Bookmark_AddFileName {
            get {
                return ResourceManager.GetString("Item_Bookmark_AddFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Item_Column_File {
            get {
                return ResourceManager.GetString("Item_Column_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Item_Directories {
            get {
                return ResourceManager.GetString("Item_Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display PDF.
        /// </summary>
        public static string Item_DisplayPdf {
            get {
                return ResourceManager.GetString("Item_DisplayPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open bookmark panel when displaying.
        /// </summary>
        public static string Item_DisplayPdf_BookmarkPanel {
            get {
                return ResourceManager.GetString("Item_DisplayPdf_BookmarkPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page layout.
        /// </summary>
        public static string Item_DisplayPdf_PageLayout {
            get {
                return ResourceManager.GetString("Item_DisplayPdf_PageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One column.
        /// </summary>
        public static string Item_DisplayPdf_PageLayout_OneColumn {
            get {
                return ResourceManager.GetString("Item_DisplayPdf_PageLayout_OneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single page.
        /// </summary>
        public static string Item_DisplayPdf_PageLayout_SinglePage {
            get {
                return ResourceManager.GetString("Item_DisplayPdf_PageLayout_SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Item_Excel {
            get {
                return ResourceManager.GetString("Item_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sheet name to bookmark.
        /// </summary>
        public static string Item_Excel_AddSheetToBookmark {
            get {
                return ResourceManager.GetString("Item_Excel_AddSheetToBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Item_Files {
            get {
                return ResourceManager.GetString("Item_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input / Output.
        /// </summary>
        public static string Item_InputOutput {
            get {
                return ResourceManager.GetString("Item_InputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete converted PDF.
        /// </summary>
        public static string Item_InputOutput_DeleteConvertedPdf {
            get {
                return ResourceManager.GetString("Item_InputOutput_DeleteConvertedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        public static string Item_InputOutput_OutputFile {
            get {
                return ResourceManager.GetString("Item_InputOutput_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directory.
        /// </summary>
        public static string Item_InputOutput_WorkingDirectory {
            get {
                return ResourceManager.GetString("Item_InputOutput_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Item_Option {
            get {
                return ResourceManager.GetString("Item_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file.
        /// </summary>
        public static string Item_OutputFile {
            get {
                return ResourceManager.GetString("Item_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Item_Property {
            get {
                return ResourceManager.GetString("Item_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Item_Property_Author {
            get {
                return ResourceManager.GetString("Item_Property_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Item_Property_Creator {
            get {
                return ResourceManager.GetString("Item_Property_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Item_Property_Keywords {
            get {
                return ResourceManager.GetString("Item_Property_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Item_Property_Subject {
            get {
                return ResourceManager.GetString("Item_Property_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Item_Property_Title {
            get {
                return ResourceManager.GetString("Item_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify target directories by regular expression.
        /// </summary>
        public static string Item_RegularExpression_Directory {
            get {
                return ResourceManager.GetString("Item_RegularExpression_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify target files by regular expression.
        /// </summary>
        public static string Item_RegularExpression_File {
            get {
                return ResourceManager.GetString("Item_RegularExpression_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the files by regular expression to exclude from the above.
        /// </summary>
        public static string Item_RegularExpression_File2 {
            get {
                return ResourceManager.GetString("Item_RegularExpression_File2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the directories by backreference of regular expression.
        /// </summary>
        public static string Item_RegularExpression_ReplaceDirectory {
            get {
                return ResourceManager.GetString("Item_RegularExpression_ReplaceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the files by backreference of regular expression.
        /// </summary>
        public static string Item_RegularExpression_ReplaceFile {
            get {
                return ResourceManager.GetString("Item_RegularExpression_ReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace directory name.
        /// </summary>
        public static string Item_ReplaceDirectoryName {
            get {
                return ResourceManager.GetString("Item_ReplaceDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace file name.
        /// </summary>
        public static string Item_ReplaceFileName {
            get {
                return ResourceManager.GetString("Item_ReplaceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Item_Target {
            get {
                return ResourceManager.GetString("Item_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Item_Word {
            get {
                return ResourceManager.GetString("Item_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create bookmarks.
        /// </summary>
        public static string Item_Word_CreateBookmarks {
            get {
                return ResourceManager.GetString("Item_Word_CreateBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from word bookmarks.
        /// </summary>
        public static string Item_Word_CreateBookmarks_FromBookmark {
            get {
                return ResourceManager.GetString("Item_Word_CreateBookmarks_FromBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from word heading.
        /// </summary>
        public static string Item_Word_CreateBookmarks_FromHeading {
            get {
                return ResourceManager.GetString("Item_Word_CreateBookmarks_FromHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Item_Word_CreateBookmarks_None {
            get {
                return ResourceManager.GetString("Item_Word_CreateBookmarks_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(_F).
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuFile_Exit {
            get {
                return ResourceManager.GetString("MenuFile_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        public static string MenuFile_OpenLogFolder {
            get {
                return ResourceManager.GetString("MenuFile_OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MenuFile_RecentFiles {
            get {
                return ResourceManager.GetString("MenuFile_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help(_H).
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuHelp_About {
            get {
                return ResourceManager.GetString("MenuHelp_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string MenuHelp_CheckForUpdates {
            get {
                return ResourceManager.GetString("MenuHelp_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string MenuHelp_Usage {
            get {
                return ResourceManager.GetString("MenuHelp_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Mode.
        /// </summary>
        public static string ModeEasy_Title {
            get {
                return ResourceManager.GetString("ModeEasy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Mode.
        /// </summary>
        public static string ModeStandard_Title {
            get {
                return ResourceManager.GetString("ModeStandard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for a while..
        /// </summary>
        public static string MsgBox_CheckForUpdates_Message {
            get {
                return ResourceManager.GetString("MsgBox_CheckForUpdates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        public static string MsgBox_CheckForUpdates_Title {
            get {
                return ResourceManager.GetString("MsgBox_CheckForUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for a while..
        /// </summary>
        public static string MsgBox_Downloading_Message {
            get {
                return ResourceManager.GetString("MsgBox_Downloading_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string MsgBox_Downloading_Title {
            get {
                return ResourceManager.GetString("MsgBox_Downloading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version..
        /// </summary>
        public static string MsgBox_NotFound_Message {
            get {
                return ResourceManager.GetString("MsgBox_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string MsgBox_NotFound_Title {
            get {
                return ResourceManager.GetString("MsgBox_NotFound_Title", resourceCulture);
            }
        }
    }
}
