//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakePdf.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MakePdf.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_BackHome {
            get {
                return ResourceManager.GetString("Common_BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Down {
            get {
                return ResourceManager.GetString("Common_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exclusion pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ExclusionPattern {
            get {
                return ResourceManager.GetString("Common_ExclusionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Load {
            get {
                return ResourceManager.GetString("Common_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_LoadSetting {
            get {
                return ResourceManager.GetString("Common_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open File Dialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFileDialog {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFileDialog_FileType_All {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_FileType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFileDialog_FileType_Json {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_FileType_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFileDialog_FileType_Pdf {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_FileType_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFileDialog_Title_LoadSetting {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_Title_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select output file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFileDialog_Title_OutputFile {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_Title_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFileDialog_Title_SaveSetting {
            get {
                return ResourceManager.GetString("Common_OpenFileDialog_Title_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open folder dialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFolderDialog {
            get {
                return ResourceManager.GetString("Common_OpenFolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select working directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFolderDialog_Title_WorkingDirectory {
            get {
                return ResourceManager.GetString("Common_OpenFolderDialog_Title_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SaveSetting {
            get {
                return ResourceManager.GetString("Common_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Start {
            get {
                return ResourceManager.GetString("Common_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_StartProcess {
            get {
                return ResourceManager.GetString("Common_StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Up {
            get {
                return ResourceManager.GetString("Common_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the working directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_DirectoryEmpty_Message_WorkingDirectory {
            get {
                return ResourceManager.GetString("Dialog_DirectoryEmpty_Message_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The directory is empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_DirectoryEmpty_Title {
            get {
                return ResourceManager.GetString("Dialog_DirectoryEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   already exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_FileExists_Message {
            get {
                return ResourceManager.GetString("Dialog_FileExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to overwrite it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_FileExists_Message_Overwrite {
            get {
                return ResourceManager.GetString("Dialog_FileExists_Message_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_FileExists_Title {
            get {
                return ResourceManager.GetString("Dialog_FileExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the output file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_FileNameEmpty_Message_OutputFile {
            get {
                return ResourceManager.GetString("Dialog_FileNameEmpty_Message_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name is empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_FileNameEmpty_Title {
            get {
                return ResourceManager.GetString("Dialog_FileNameEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file does not exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_FileNotExists_Message_SettingFile {
            get {
                return ResourceManager.GetString("Dialog_FileNotExists_Message_SettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file does not exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_FileNotExists_Title {
            get {
                return ResourceManager.GetString("Dialog_FileNotExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewVersionFound_CurrentVersion {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Later に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewVersionFound_Later {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The new version is available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewVersionFound_Message1 {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to update now ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewVersionFound_Message2 {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewVersionFound_NewVersion {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New version found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewVersionFound_Title {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewVersionFound_Update {
            get {
                return ResourceManager.GetString("Dialog_NewVersionFound_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait for a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Processing_Message {
            get {
                return ResourceManager.GetString("Dialog_Processing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Processing_Title {
            get {
                return ResourceManager.GetString("Dialog_Processing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFile_Exit {
            get {
                return ResourceManager.GetString("MenuFile_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp_About {
            get {
                return ResourceManager.GetString("MenuHelp_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for Updates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp_CheckForUpdates {
            get {
                return ResourceManager.GetString("MenuHelp_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp_Usage {
            get {
                return ResourceManager.GetString("MenuHelp_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeEasy_Column_Filename {
            get {
                return ResourceManager.GetString("ModeEasy_Column_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeEasy_Column_Path {
            get {
                return ResourceManager.GetString("ModeEasy_Column_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeEasy_OutputFile {
            get {
                return ResourceManager.GetString("ModeEasy_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Easy Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeEasy_Title {
            get {
                return ResourceManager.GetString("ModeEasy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_After {
            get {
                return ResourceManager.GetString("ModeStandard_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All directories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_AllDirectories {
            get {
                return ResourceManager.GetString("ModeStandard_AllDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All supported files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_AllSupportedFiles {
            get {
                return ResourceManager.GetString("ModeStandard_AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Before に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Before {
            get {
                return ResourceManager.GetString("ModeStandard_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bookmark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Bookmark {
            get {
                return ResourceManager.GetString("ModeStandard_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add directory name to bookmark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Bookmark_AddDirectoryName {
            get {
                return ResourceManager.GetString("ModeStandard_Bookmark_AddDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add file name to bookmark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Bookmark_AddFileName {
            get {
                return ResourceManager.GetString("ModeStandard_Bookmark_AddFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Directories {
            get {
                return ResourceManager.GetString("ModeStandard_Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_DisplayPdf {
            get {
                return ResourceManager.GetString("ModeStandard_DisplayPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open bookmark panel when displaying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_DisplayPdf_BookmarkPanel {
            get {
                return ResourceManager.GetString("ModeStandard_DisplayPdf_BookmarkPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_DisplayPdf_PageLayout {
            get {
                return ResourceManager.GetString("ModeStandard_DisplayPdf_PageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_DisplayPdf_PageLayout_OneColumn {
            get {
                return ResourceManager.GetString("ModeStandard_DisplayPdf_PageLayout_OneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_DisplayPdf_PageLayout_SinglePage {
            get {
                return ResourceManager.GetString("ModeStandard_DisplayPdf_PageLayout_SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Excel {
            get {
                return ResourceManager.GetString("ModeStandard_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add sheet name to bookmark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Excel_AddSheetToBookmark {
            get {
                return ResourceManager.GetString("ModeStandard_Excel_AddSheetToBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Files {
            get {
                return ResourceManager.GetString("ModeStandard_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input / Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_InputOutput {
            get {
                return ResourceManager.GetString("ModeStandard_InputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete converted PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_InputOutput_DeleteConvertedPdf {
            get {
                return ResourceManager.GetString("ModeStandard_InputOutput_DeleteConvertedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_InputOutput_OutputFile {
            get {
                return ResourceManager.GetString("ModeStandard_InputOutput_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_InputOutput_WorkingDirectory {
            get {
                return ResourceManager.GetString("ModeStandard_InputOutput_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Property {
            get {
                return ResourceManager.GetString("ModeStandard_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Property_Author {
            get {
                return ResourceManager.GetString("ModeStandard_Property_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Property_Creator {
            get {
                return ResourceManager.GetString("ModeStandard_Property_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keywords に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Property_Keywords {
            get {
                return ResourceManager.GetString("ModeStandard_Property_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Property_Subject {
            get {
                return ResourceManager.GetString("ModeStandard_Property_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Property_Title {
            get {
                return ResourceManager.GetString("ModeStandard_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify target directories by regular expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_RegularExpression_Directory {
            get {
                return ResourceManager.GetString("ModeStandard_RegularExpression_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify target files by regular expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_RegularExpression_File {
            get {
                return ResourceManager.GetString("ModeStandard_RegularExpression_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the files by regular expression to exclude from the above に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_RegularExpression_File2 {
            get {
                return ResourceManager.GetString("ModeStandard_RegularExpression_File2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the directories by backreference of regular expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_RegularExpression_ReplaceDirectory {
            get {
                return ResourceManager.GetString("ModeStandard_RegularExpression_ReplaceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the files by backreference of regular expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_RegularExpression_ReplaceFile {
            get {
                return ResourceManager.GetString("ModeStandard_RegularExpression_ReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace directory name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_ReplaceDirectoryName {
            get {
                return ResourceManager.GetString("ModeStandard_ReplaceDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace file name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_ReplaceFileName {
            get {
                return ResourceManager.GetString("ModeStandard_ReplaceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Target {
            get {
                return ResourceManager.GetString("ModeStandard_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Title {
            get {
                return ResourceManager.GetString("ModeStandard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Word {
            get {
                return ResourceManager.GetString("ModeStandard_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create bookmarks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Word_CreateBookmarks {
            get {
                return ResourceManager.GetString("ModeStandard_Word_CreateBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   from word bookmarks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Word_CreateBookmarks_FromBookmark {
            get {
                return ResourceManager.GetString("ModeStandard_Word_CreateBookmarks_FromBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   from word heading に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeStandard_Word_CreateBookmarks_FromHeading {
            get {
                return ResourceManager.GetString("ModeStandard_Word_CreateBookmarks_FromHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait for a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBox_CheckForUpdates_Message {
            get {
                return ResourceManager.GetString("MsgBox_CheckForUpdates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for updates... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBox_CheckForUpdates_Title {
            get {
                return ResourceManager.GetString("MsgBox_CheckForUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait for a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBox_Downloading_Message {
            get {
                return ResourceManager.GetString("MsgBox_Downloading_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBox_Downloading_Title {
            get {
                return ResourceManager.GetString("MsgBox_Downloading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using the latest version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBox_NotFound_Message {
            get {
                return ResourceManager.GetString("MsgBox_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBox_NotFound_Title {
            get {
                return ResourceManager.GetString("MsgBox_NotFound_Title", resourceCulture);
            }
        }
    }
}
